spring:
  application:
    name: voice-server-api #应用名称,与application.properities中保持一致
  session:
    store-type: none
#  rabbitmq:
#    host: 10.105.85.56
#    port: 5672
#    username: bmdb
#    password: bmdb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#datasource config
ds:
 driverClassName: com.mysql.jdbc.Driver
 url: jdbc:mysql://127.0.0.1:3306/voice-cloud?useUnicode=true&amp;characterEncoding=utf-8
 username: root
 password: root
 initialSize: 10
 minIdle: 10
 maxIdle: 15
 maxActive: 15
 maxWait: 1000
 testOnBorrow: false
 testWhileIdle: true
 timeBetweenEvictionRunsMillis: 10000
 numTestsPerEvictionRun: 3
 minEvictableIdleTimeMillis: 300000

#redis
jedis:
  host: 127.0.0.1
  port: 6379
  maxTotal: 100
  maxIdle: 50
  maxWaitMillis: 1000

#文件上传
upload:
  path: /usr/local/nginx/html

#h5地址
h5:
 app:
  url:
   path: http://192.168.2.122


server:
  port: 5001  #Tomcat端口
  max-http-header-size: 4194304
  tomcat:
    max-http-post-size: 0


#服务注册与发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2001/eureka/  #Eureka Server

  #服务注册时，在Eureka的实例配置
  #metadata-map.cluster：指定服务集群名称（一个服务集群包括多个app）
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info
    metadata-map:
      cluster: MAIN

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  #Feign超时时间

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: countSql

